import Head from "next/head"
import Image from "next/image"
import Link from "next/link"


function Login() {
  return (
    <>
    <div className="relative flex h-screen w-screen flex-col bg-[#000000] md:items-center
    md:justify-center md:bg-transparent">      
        <Head>
            <title>Login - JL+</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="images/logo.svg" />
        </Head>
        <Image
            src="https://rb.gy/p2hphi"
            layout="fill"
            className="-z-10 !hidden opacity-60 sm:!inline"
            objectFit="cover"
            alt=""
        />
        <img
            src="../images/jl_logo.svg"
            width={100}
            height={100}
            className="cursor-pointer object-contain" 
            alt={""}            
        />
        <form className="relative mt-24 space-y-8 rounded bg-black/75 py-10 px-6
        md:mt-0 md:max-w-md:px-14">
            <h1 className="text-4xl font-semibold"> Sign In </h1>
            <div className="space-y-4">
                <label className="inline-block w-full">
                    <input type="email" placeholder="Email" className="input" />
                </label>
                <label className="inline-block w-full">
                    <input type="password" placeholder="Password" className="input" />
                </label>
            </div>
            <button className="w-full rounded bg-[#044cd0] py-3 font-semibold hover:bg-[#3267c9]">
                <Link href="/">
                Sign In
                </Link>
            </button>

            <div className="text-[gray]">
                New to JL+?{' '} 
                <button className="text-white hover:underline hover:text-[#044cd0]"> Sign Up Now!</button>
            </div>

        </form>
    </div>
    </>
  )
}

export default Login